# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView  # Added This file manually

class Ui_webDialog(object):
    def __init__(self, webDialog):
        webDialog.setObjectName("webDialog")
        webDialog.resize(721, 571)
        self.gridLayout = QtWidgets.QGridLayout(webDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.webBrowser = QWebEngineView(webDialog)
        self.webBrowser.setUrl(QtCore.QUrl("about:blank"))
        self.webBrowser.setObjectName("webBrowser")
        self.gridLayout.addWidget(self.webBrowser, 0, 0, 1, 1)

        self.retranslateUi(webDialog)
        QtCore.QMetaObject.connectSlotsByName(webDialog)

    def retranslateUi(self, webDialog):
        _translate = QtCore.QCoreApplication.translate
        webDialog.setWindowTitle(_translate("webDialog", "Browser"))
